### ISSUE TITLE
Keep receiving 429 from API

### ISSUE THREAD

**Issue by ha-ku** [Universalis-FFXIV/Universalis#548]
The Doc says there's a ratelimit of 14 req/s on API. Is the ratelimit relevant with number of IDs sent per http request? Does it mean 14 req/s per API or 14 req/s for all APIs? I still receive 429 respond even when I just send 1 req/s with 12 IDs.

Node Log:
```
Dec 30 09:51:02 node[266168]: https://universalis.app/api/LuXingNiao/27726,27954,27817,19958,19959,21085,22417,22418,23179,24240,24255,24241  returns  429
Dec 30 09:51:03 node[266168]: https://universalis.app/api/history/ChenXiWangZuo/27726,27954,27817,19958,19959,21085,22417,22418,23179,24240,24255,24241  returns  429
Dec 30 09:51:04 node[266168]: https://universalis.app/api/history/ChenXiWangZuo/27726,27954,27817,19958,19959,21085,22417,22418,23179,24240,24255,24241  returns  429
Dec 30 09:51:05 node[266168]: https://universalis.app/api/ChenXiWangZuo/27801,27696,27697,27727,27968,27698,27728,27699,27803,27729,27700,27776  returns  429
Dec 30 09:51:06 node[266168]: https://universalis.app/api/history/LuXingNiao/27701,27730,27782,27702,27703,27731,27704,27705,28717,29968,29970,29976  returns  429
Dec 30 09:51:07 node[266168]: https://universalis.app/api/ChenXiWangZuo/2,3,4,5,6,7,5106,5488,5432,5107,5128,5133  returns  429
Dec 30 09:51:08 node[266168]: https://universalis.app/api/ChenXiWangZuo/2,3,4,5,6,7,5106,5488,5432,5107,5128,5133  returns  429
```

By the way, are there any plans about API keys in the near future?

**Comment by karashiiro** [comment]
Given that adding the rate limit reduced my monthly bandwidth by more than a terabyte, I’d say that it’s relevant. It’s 14r/s across all APIs, though, so that’s weird. Do you have Teamcraft or something else making requests on your IP address at the same time as that?

Once this DO billing cycle is over I’m going to change hosting providers, and I’ll be at least temporarily removing the rate limit then to see if I can support that without incurring overages. Failing that, I do intend to add API keys, it’s just low on the list of priorities right now.

**Comment by ha-ku** [comment]
I found out the reason. My requests aren't accurate enough, thus the server has to take much more time to generate the response. When more requests come in than requests being handled, it eventually leads to an excess of rate limit. Thanks for helping!
